### ISSUE TITLE
Fix account slug in weblink

### ISSUE THREAD

**Issue by ndowmon** [JupiterOne/graph-cobalt#9]
Cobalt asset web links are prefixed with their account like `https://app.cobalt.io/{{ accountSlug }}`. The JupiterOne integration takes a naive approach to building this `accountSlug` property:

https://github.com/JupiterOne/graph-cobalt/blob/master/src/steps/account.ts#L27
```ts
  await apiClient.getAccount(async (org) => {
    delete org.resource.token;
    const orgProps = org.resource;
    const webLink: string = `https://app.cobalt.io/${webifyFromTitles(
      orgProps.name,
    )}`;
```

The `org.resource.name` can be converted into `accountSlug` in some cases, but is unreliable. JupiterOne could allow users to pass an optional `accountSlug` property into the integration that can allow reliable web links to be created.

The Cobalt API does not currently return web URLs or the `accountSlug` property, but if this is available in their APIs in the future, we should leverage Cobalt's own API for more reliable web links.

**Comment by nktrk** [comment]
@ndowmon will update here when this becomes available in the Cobalt API. It will also be the case for `pentest.resource.title` as that is used in other contexts to build a `webLink`

**Comment by nktrk** [comment]
@ndowmon I've got an update here for you. Now in the API we are including a redirect web app link for the following endpoints:

- [/orgs](https://docs.cobalt.io/#orgs)
- [/pentests](https://docs.cobalt.io/#pentests) 
- [/findings](https://docs.cobalt.io/#findings)

It's nested under the links.ui.url field which I've pointed to in our docs site for each bullet above. You will not have to guess or construct the URL yourself and can now use this field in it's place.

Let me know if you have any questions.
